name: Release

# タグの生成をトリガーに以下を実施する。
# 1. パッケージのzipファイルを作成
#    - `/Packages`以下の各パッケージディレクトリからzipを`{name}-{x.y.z}.zip`として作成
# 2. package.jsonを作成
#    - 各`/Packages/*/package.json`を`{name}-{x.y.z}.json`として作成
# 3. GitHub ReleaseのAssetsとしてアップロード
# 4. VPMリポジトリにパッケージをプッシュ

# VPMリポジトリへのプッシュには、create-github-app-tokenを使用して、GitHub Appのトークンを取得し、VPMリポジトリにアクセスする。
# create-github-app-tokenを使用するため、APP_IDとPRIVATE_KEYをGitHub Secretsに設定する必要がある。

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (e.g., 1.2.3)'
        required: true
        default: '0.0.0-test'
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      # Checkout
      - uses: actions/checkout@v5
        with:
          path: 'main-repo'
          submodules: true

      # Set environment Variables
      - name: Set Environment Variables
        id: set-version
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            VERSION=$(echo "${GITHUB_REF}" | sed 's#refs/tags/v##')
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Release version set to: ${VERSION}"

      # Create package
      - name: Create Package Zip
        id: make_zip
        run: |
          set -e
          mkdir -p release
          
          for package_dir in $(find ./main-repo/Packages -maxdepth 2 -name 'package.json' -exec dirname {} \;); do
            # パッケージ名を取得 
            package_name=$(basename "$package_dir")
            zip_file="release/${package_name}-${{ steps.set-version.outputs.version }}.zip"
            json_file="release/${package_name}-${{ steps.set-version.outputs.version }}.json"
            
            echo "-> Creating zip for '${package_name}' at '${zip_file}'"
            # zipファイルを作成
            # サブシェルを使用して、現在のディレクトリを変更しないようにする
            (cd "$package_dir" && zip -r "$OLDPWD/${zip_file}" . -x ".git/*")
          
            echo "-> Copying package.json for '${package_name}' to '${json_file}'"
            cp "${package_dir}/package.json" "${json_file}"
          done
      - name: Check Package Zip
        run:  echo ${{steps.make_zip.outputs.files}}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          # The body of the release. You can customize this.
          body: "Release version v${{ steps.set-version.outputs.version }}"
          # Upload all files from the 'release' directory as release assets.
          files: release/*
          # The name of the release.
          name: "Release v${{ steps.set-version.outputs.version }}"
          # The tag name for the release. The action infers this from the event.
          tag_name: ${{ github.ref_name }}

  push-to-vpm:
    needs: create-release # run after asset upload
    runs-on: ubuntu-latest
    steps:
      # Checkout VPM Repository
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout VPM Repository
        uses: actions/checkout@v5
        with:
          repository: 'VirtualAviationJapan/vpm'
          path: 'vpm-repo'
          token: ${{ steps.app-token.outputs.token }}

      - name: Copy artifact to target repository
        uses: robinraju/release-downloader@v1
        with:
          tag: "v${{ needs.create-release.outputs.version }}"
          fileName: "*.json"
          out-file-path: "vpm-repo/packages"
          extract: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          path: vpm-repo
          commit-message: "add: URC-Redux v${{ needs.create-release.outputs.version }} packages"
          title: "Update URC-Redux packages to v${{ needs.create-release.outputs.version }}"
          body: This PR updates the URC-Redux packages to version v${{ needs.create-release.outputs.version }}.
          branch: "update-urc-redux-packages-${{ needs.create-release.outputs.version }}"
          base: "master"
          delete-branch: 'true'